### ISSUE TITLE
Craft Oak Boat Broken

### ISSUE THREAD

**Issue by Aikirob** [gamerpotion/DarkQuesting#1]
Cannot progress Due to Craft Oak Boat Quest being broken, does nothing when you craft the boat...
tested with fabric 1.19

**Comment by gamerpotion** [comment]
> Cannot progress Due to Craft Oak Boat Quest being broken, does nothing when you craft the boat... tested with fabric 1.19

Hi,  this issue was fixed in version 1.0.1  please could you update to that, we were made aware of this yesterday and updated the mod.
