### ISSUE TITLE
game breaking bug

### ISSUE THREAD

**Issue by Aikirob** [gamerpotion/DarkQuesting#2]
I had 50 bones in my inventory, when I got to the skeleton advancements they did not fire the plaque, so i dropped them on the ground and they didnt appear, just disappeared from my inventory completely, from then on I couldnt use or drop any items at all. its like my inventory broke entirely.

**Comment by gamerpotion** [comment]
> I had 50 bones in my inventory, when I got to the skeleton advancements they did not fire the plaque, so i dropped them on the ground and they didnt appear, just disappeared from my inventory completely, from then on I couldnt use or drop any items at all. its like my inventory broke entirely.

Hi do you have any other mods installed?  This mod doesn't affect the inventory behavior as its only advancement based

If you have the bones in hotbar you can just move to inventory and back to trigger the game to recognize it.

**Comment by Aikirob** [comment]
Yes, I am using other mods, I'll try to reproduce it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gamerpotion** [comment]
ok thanks, please post back once that is done,
closing for now.
